name: Run main.py at 6 AM IST

on:
  schedule:
    - cron: '30 22 * * 0'  # Every Sunday 10:30 PM UTC = Monday 4:00 AM IST
  workflow_dispatch:

permissions:
  contents: write   # allow committing back to repo

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome and WebDriver
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Install dependencies
      run: pip install -r .\requirements

    - name: Run main.py
      run: python .\main.py

    - name: Commit and Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "Auto-update on $(date)" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin HEAD:main
